<?php
return array (
// // Charts Translation File

// // Button Text

// // Labels
'Date Range'=>'Datumsbereich',
'Data Summary'=>'Zusammenfassung Daten',
'Total Records'=>'Einträge insgesamt',
'Total Value'=>'Gesamtwert',
'Projected Value'=>'Prognostizierter Wert',
'Current Value'=>'Aktueller Wert',
'Grid Builder'=>'Grid Builder',
'Lead Performance'=>'Lead Performance',
'Saved Reports'=>'Gespeicherte Berichte',
'Deal Report'=>'Deal Bericht',
'User Activity'=>'Benutzer-Aktivität',
'Row Field'=>'Zeile Feld',
'Column Field'=>'Spalte Feld',
'Hide empty rows/columns?'=>'Verberge leere Zeilen / Spalten?',
'Cell Data Type'=>'Zellen-Typ',
'Count'=>'Zählen',
'Sum'=>'Summe',
'Average'=>'Durchschnitt',
'Cell Data Field'=>'Zellen-Feld',
'(none)'=>'(none)',
'pie'=>'Pie',
'bar'=>'Bar',
'Save Report'=>'Bericht speichern',
'Print Report'=>'Bericht drucken',
'Email Report'=>'Bericht mailen',
'Strict Mode'=>'Strict Mode',
'Field'=>'Feld',
'View Report'=>'Bericht anzeigen',
'Grid'=>'Grid',
'Deal'=>'Deal',
'Actions Due'=>'Aufgaben bis',
'Lead Volume'=>'Lead Volumen',
'Pipeline'=>'Pipeline',
'Select leads received in the last'=>'Wählen Sie Leads, die erhalten wurden in der/den letzte(n)',
'Lead Distribution and Status'=>'Lead-Verteilung und Status',
'Lead Conversion'=>'Lead-Konvertierung',
'Lead Received'=>'Lead erhalten',
'Pipeline Dashboard'=>'Pipeline-Dashboard',
'Select deals closing in'=>'Wähle Angebote mit Abschluß',
'Limit to confidence is'=>'Vertrauen beschränken auf',
'Limit selected deals to'=>'Wähle Angebote mit Abschluß',
'Select deals assigned to'=>'Wähle Angebote zugeordnet',
'Opportunities Dashboard'=>'Chancen-Dashboard',
'Select deals with status'=>'Wähle Angebote mit Status',

// // Data Options
'Last Week'=>'letzte Woche',
'Last Month'=>'letzter Monat',
'This Year'=>'dieses Jahr',
'Last Year'=>'letztes Jahr',
'All Time'=>'jederzeit',
'Growing'=>'zunehmend',
'Forecast'=>'Vorhersage',
'Committed'=>'committed',
'In The Bag'=>'in der Tasche',
'Smallest'=>'kleinste',
'Largest'=>'größte',
'Others'=>'andere',
'Deals'=>'Angebote',
'Days To Close'=>'Tage zum Abschluß',
'Date Closing'=>'Datum Abschluß',

// // Report Attributes
'Report Type'=>'Bericht Typ',
'Rows'=>'Zeilen',
'Ignore Zeros?'=>'Ignoriere Nullwerte?',
'Data Type'=>'Datentyp',
'Lead Activity'=>'Lead-Aktivität',
'Lead Sources'=>'Lead-Quellen',
'Last Quarter'=>'das letzte Viertel',
'Unknown'=>'unbekannt',
'Limit To'=>'beschränken auf',
'Widget Dashboard'=>'Widget-Dashboard',
);