<?php
return array (
// Profile Attributes
'Tag Line'=>'Tag Line',
'Allow users to post on your profile?'=>'Benutzern erlauben, in Ihr Profil zu schreiben?',
'Language'=>'Sprache',
'Enable group chat?'=>'Aktiviere Gruppen Chat?',
'Widgets'=>'Widgets',
'Menu Color'=>'Menü Hintergrundfarbe',
'Background Image'=>'Hintergrundbild',
'Start Page'=>'Startseite',
'Results Per Page'=>'Ergebnisse Pro Seite',
'Show Social Media'=>'Zeige Soziale Medien',
'Upload a Background'=>'Laden Sie einen Hintergrund hoch',
'Avatar'=>'Avatar',
'Widget Order'=>'Widget Auftrag',
'Widget Settings'=>'Widget Einstellungen',
'Page Opacity'=>'Seite Abtönung',
'Show Detail View'=>'Zeige Detailansicht',
'Show Workflow'=>'Zeige Workflow',
'Gridview Settings'=>'Gridview Einstellungen',
'Form Settings'=>'Formular Einstellungen',
'Email Signature'=>'E-Mail Signatur',
'My Signature'=>'Meine Signatur',
'Enable Full Width Layout'=>'Ganzseitiges Layout verwenden',
'Google ID'=>'Google ID',
'Signature'=>'Unterschrift',
'Use my signature'=>'Meine Signatur verwenden',
'Use default'=>'Standardeinstellungen verwenden',
'Old Password'=>'Altes Passwort',
'New Password'=>'Neue Passwort',
'Confirm New Password'=>'Neues Passwort bestätigen',

// Profile Actions
'View Profile'=>'Profil Anzeigen',
'Update Profile'=>'Profil Aktualisieren',
'Change Settings'=>'Einstellungen Ändern',
'People'=>'Menschen',
'Change Personal Settings'=>'Ändern Sie Ihre persönliche Einstellungen',
'Change Password'=>'Kennwort ändern',
'Reset Widgets'=>'Widgets zurücksetzen',
'Manage Apps'=>'Apps verwalten',

// Profile Titles
'Profile:'=>'Profil:',
'Update Your Profile'=>'Aktualisieren Sie Ihr Profil',
'Unhide Tags'=>'Schlagworte einblenden',
'Change Password Form'=>'Kennwort ändern',

// Social
'Feed'=>'Feed',
'Reply'=>'Antwort',
'A larger Chat Box'=>'Größere Chat Box',
'A blog-like discussion forum'=>'Ein Blog-ähnliches Diskussionsforum',

// Misc
'This user does not allow posting on their feed.'=>'Dieser Benutzer erlaubt es nicht, dass Sie auf seine Feeds antworten.',
'Save your current theme settings as a predefined theme.'=>'Speichern Sie Ihre aktuellen Theme-Einstellungen als Vorlage.',
'Update the settings of the currently selected predefined theme.'=>'Aktualisieren Sie die Einstellungen des aktuell ausgewählten, vordefinierten Themes.',
'Create Theme'=>'Neues Theme',
'Save Theme'=>'Theme speichern',
'Upload Background Image'=>'Hintergrundbild hochladen',
'Login Sound'=>'Anmelde-Sound',
'Upload a Login Sound'=>'Laden Sie ein Anmelde-Sound hoch',
'Upload Login Sound'=>'Anmelde-Sound hochladen',
'Notification Sound'=>'Benachrichtigungs-Sound',
'Upload Notification Sound'=>'Benachrichtigungs-Sound hochladen',
'Upload a Notification Sound'=>'Einen Benachrichtigungs-Sound hochladen',
'Create a Theme'=>'Erstellen Sie ein Theme',
'Upload a Background Image'=>'Ein Hintergrundbild hochladen',
'Export Theme'=>'Theme exportieren',
'Upload Theme'=>'Theme hochladen',
'Manage Passwords for Third-Party Applications'=>'Kennwörter verwalten für Anwendungen von Drittanbietern',
'Send E-Mail'=>'E-Mail senden',
'Choose Picture'=>'Bild auswählen',
'Theme saved successfully.'=>'Theme erfolgreich gespeichert.',
'Theme name already exists or is invalid.'=>'Theme-Name bereits oder ist ungültig.',
'Theme created successfully.'=>'Theme erfolgreich erstellt.',
'Page Header Color'=>'Seitenkopf Farbe',
'Edit Profile'=>'Profil bearbeiten',
'Disable phone field links?'=>'Deaktiviere Telefonfeld-Links?',
'Disable notifications pop-up?'=>'Deaktiviere Pop-up Benachrichtigung?',
'Upload a theme that has been exported with the theme import tool.'=>'Laden Sie ein Theme hoch, das mit diesem Tool exportiert wurde.',
'Maximize'=>'Maximieren',
'Add Profile Widget'=>'Profil Widget hinzufügen',
'Active User'=>'Angemeldete Benutzer',
'Inactive User'=>'Nicht angemeldete Benutzer',
'Import Theme'=>'Theme importieren',
'Comment on this post'=>'Kommentar zu diesem Beitrag',
'View comments'=>'Kommentare anzeigen',
'Make unimportant'=>'Als unwichtig markieren',
'Broadcase Event'=>'Broadcase Event',
'Create Activity Feed Report Email'=>'Erstelle Aktivitäten-Feed Report per E-Mail',
'This form will allow you to create a periodic email with information about events in the Activity Feed.'=>'Dieses Formular ermöglicht es Ihnen, eine regelmäßige E-Mail mit Informationen über Veranstaltungen im Aktivitäten-Feed zu erstellen.',
'The filters you had checked on the previous page will be used to determine which content to give you information about.'=>'Die Filter, die Sie auf der vorherigen Seite gewählt haben werden verwendet, um zu bestimmen über welche Informationen Sie weitergeben wollen.',
'Please note that this report will not function if you do not have the Cron service turned on, please check with your administrator if you are unsure.'=>'Bitte beachten Sie, dass dieser Report nicht funktioniert, wenn der Cron-Dienst nicht aktiviert ist. Bitte fragen Sie Ihren Administrator, wenn Sie sich unsicher sind.',
'Report Settings'=>'Report-Einstellungen',
'Select a Document'=>'Wählen Sie ein Dokument',
'Enter the name of a Doc:'=>'Geben Sie den Namen eines Dokuments ein:',
'Select a Doc'=>'Wählen Sie ein Dokument',
'Please select an existing Doc'=>'Bitte wählen Sie ein vorhandenes Dokument',
'Theme imported successfully'=>'Theme erfolgreich importiert',
'You will no longer receive this activity feed report.'=>'Sie werden diesen Aktivitäts-Feed Report nicht mehr erhalten.',
'You do not have permission to delete this activity feed report.'=>'Sie haben keine Berechtigung, diesen Aktivitäts-Feed Report zu löschen.',
'Invalid template'=>'Ungültige Vorlage',
'Profile not found'=>'Profil nicht gefunden',
'Extension'=>'Erweiterung',
'Disable automatic record tagging?'=>'Automatisches Datensatz-Kennzeichnung deaktivieren?',
'Disable timer display in page title?'=>'Die Timer-Anzeige im Seitentitel deaktivieren?',
'Activity Feed Report'=>'Aktivitäts-Feed Report',
'Here\'s your {range} update on what\'s been going on in X2Engine!'=>'Hier ist Ihr {range} Update, was in X2Engine passiert!',
'Top Activity'=>'Top Aktivitäten',
'Top Users'=>'Top Benutzer',
'events from'=>'Ereignisse aus',
'Here\'s the 10 most recent items on the Activity Feed.'=>'Hier sind die 10 jüngsten Einträge aus dem Aktivitäts-Feed.',
'To stop receiving this report, '=>'Um diesen Report nicht weiter zu erhalten,',
'click here'=>'klicken Sie hier',
);